apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/ysooun'
    path: '/y-s-moyur-app'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
