apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://your-git-repo-url'
    path: '/path-to-your-app'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
