apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: moyur-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: cloud.aws.credentials.accessKey
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: accessKey
            - name: cloud.aws.credentials.secretKey
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: secretKey
            - name: cloud.aws.s3.bucket
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: s3Bucket
            - name: cloud.aws.region.static
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: region
            - name: SPRING_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: moyur-secret
                  key: spring.jwt.secret
            spring:
              jpa:
                hibernate:
                  ddl-auto: update
